[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--no-frozen-lockfile"

[[redirects]]
  from = "/images/logo-email.png"
  to = "/logo-horizontal.png"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
